apiVersion: v1
kind: Namespace
metadata:
  name: burgerapp-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerapp-backend
  namespace: burgerapp-prod
  labels:
    app: burgerapp-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: burgerapp-backend
  template:
    metadata:
      labels:
        app: burgerapp-backend
    spec:
      containers:
        - name: backend
          image: myregistry.azurecr.io/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

